### PR TITLE
Leashed Pets (Fixes maybe?)

### PR DESCRIPTION
**Pull request by GlitchPlayer**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.
- [x] This PR has descriptive titles for commits - don't use "Updated <file-name>" as your title for all your commits in the PR.

## Pull Request Description
I tested the plugin on genisys server software without leads connecting to them.

However, in other server software. I haven't tested it. Leads might appear on other server softwares.
I'm not 100% sure about this fix

Maybe someone wanna try to test this commit?

## Optional information
I found this code block used on the NPC plugins.

20 => [2,86],
23 => [7, -1],
24 => [0, 0]

### CODE REVIEW

**Comment by jasonwynn10** [comment]
what is that change going to help?

**Comment by GlitchPlayer** [comment]
It removes leads from pets. I'm not sure on this. Do not merge if not needed

**Comment by jasonwynn10** [comment]
I noticed that the beta test server is having lead problems, could this be why?

**Comment by GlitchPlayer** [comment]
Maybe, download the branch I committed if this fixes it

**Pull request merged**
